version: "3.8"

services:
  frontend:
    image: adityagaur15/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    

    
  backend:
    image: adityagaur15/backend
    container_name: backend
    ports:
      - "8090:8090"
